'use client'

import { useCallback, useEffect, useMemo, useState } from "react";
import { Archive, Bell, Check, CircleDashed, Clock3, LayoutDashboard, Menu, Plus, Search, Sparkles, Trash2, Users, X, Zap } from "lucide-react";

type Project = { id: number; name: string; color: string };
type Status = "todo" | "in-progress" | "done";
type Priority = "low" | "medium" | "high";
type Task = { id: number; project_id: number; title: string; description: string; priority: Priority; status: Status; assignee: string };
const statuses: { id: Status; label: string; icon: typeof Clock3; color: string }[] = [
  { id: "todo", label: "To do", icon: CircleDashed, color: "bg-slate-400" }, { id: "in-progress", label: "In progress", icon: Clock3, color: "bg-sky-500" }, { id: "done", label: "Done", icon: Check, color: "bg-emerald-500" },
];
const priorityStyles = { high: "border-l-rose-500 bg-rose-50 text-rose-700", medium: "border-l-amber-400 bg-amber-50 text-amber-700", low: "border-l-emerald-500 bg-emerald-50 text-emerald-700" };

export default function Home() {
  const [projects, setProjects] = useState<Project[]>([]), [activeId, setActiveId] = useState<number | null>(null), [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true), [taskOpen, setTaskOpen] = useState(false), [projectOpen, setProjectOpen] = useState(false), [mobileOpen, setMobileOpen] = useState(false);
  const [search, setSearch] = useState(""), [dragged, setDragged] = useState<number | null>(null);
  const loadProjects = useCallback(async () => { const data = await fetch("/api/projects").then(r => r.json()); setProjects(data); setActiveId(current => current ?? data[0]?.id ?? null); }, []);
  const loadTasks = useCallback(async () => { if (!activeId) return; const data = await fetch(`/api/tasks?projectId=${activeId}`).then(r => r.json()); setTasks(data); setLoading(false); }, [activeId]);
  useEffect(() => { loadProjects(); }, [loadProjects]); useEffect(() => { loadTasks(); }, [loadTasks]);
  const active = projects.find(p => p.id === activeId), filtered = useMemo(() => tasks.filter(t => `${t.title} ${t.description}`.toLowerCase().includes(search.toLowerCase())), [tasks, search]);
  const counts = Object.fromEntries(statuses.map(s => [s.id, tasks.filter(t => t.status === s.id).length])); const completion = tasks.length ? Math.round((counts.done / tasks.length) * 100) : 0;
  async function moveTask(id: number, status: Status) { const before = tasks; setTasks(current => current.map(t => t.id === id ? { ...t, status } : t)); const res = await fetch(`/api/tasks/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (!res.ok) setTasks(before); else loadTasks(); }
  async function removeTask(id: number) { await fetch(`/api/tasks/${id}`, { method: "DELETE" }); loadTasks(); }
  async function archiveProject() { if (!activeId) return; await fetch(`/api/projects/${activeId}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ archived: true }) }); setActiveId(null); await loadProjects(); }

  return <main className="min-h-screen bg-brand-canvas text-slate-800">
    <header className="sticky top-0 z-40 flex h-16 items-center border-b border-slate-200 bg-white/90 px-4 backdrop-blur-xl lg:px-7">
      <button onClick={() => setMobileOpen(!mobileOpen)} className="mr-3 rounded-lg p-2 text-slate-500 hover:bg-slate-100 lg:hidden" aria-label="Toggle navigation"><Menu size={20}/></button>
      <div className="flex items-center gap-2.5 lg:w-60"><div className="grid size-9 place-items-center rounded-xl bg-sky-500 text-white shadow-lg shadow-sky-200"><Zap size={19} fill="currentColor"/></div><span className="font-heading text-lg font-extrabold tracking-tight">TaskFlow</span></div>
      <div className="mx-auto hidden max-w-md flex-1 items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 px-3 py-2 md:flex"><Search size={17} className="text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search tasks"/><kbd className="rounded border bg-white px-1.5 text-[10px] text-slate-400">⌘ K</kbd></div>
      <div className="ml-auto flex items-center gap-2"><button className="relative rounded-xl p-2.5 text-slate-500 hover:bg-slate-100" onClick={() => alert("You are all caught up")} aria-label="Notifications"><Bell size={19}/><span className="absolute right-2 top-2 size-2 rounded-full bg-sky-500 ring-2 ring-white"/></button><button onClick={() => alert("Account settings are ready for your profile")} className="grid size-9 place-items-center rounded-full bg-gradient-to-br from-violet-500 to-sky-500 text-xs font-bold text-white">AM</button></div>
    </header>
    <div className="flex min-h-[calc(100vh-4rem)]">
      <aside className={`${mobileOpen ? "opacity-100 translate-y-0 pointer-events-auto" : "opacity-0 -translate-y-4 pointer-events-none"} fixed inset-x-3 top-[4.5rem] z-30 rounded-2xl border bg-white p-4 shadow-xl transition-all duration-500 ease-[cubic-bezier(0.16,1,0.3,1)] lg:pointer-events-auto lg:static lg:block lg:w-64 lg:translate-y-0 lg:rounded-none lg:border-0 lg:border-r lg:opacity-100 lg:shadow-none`}>
        <nav className="space-y-1"><button onClick={() => setMobileOpen(false)} className="flex w-full items-center gap-3 rounded-xl bg-sky-50 px-3 py-2.5 text-sm font-semibold text-sky-700"><LayoutDashboard size={18}/>My workspace</button><button onClick={() => alert("Team invitations are available on the Team plan")} className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-500 hover:bg-slate-50"><Users size={18}/>Team members</button></nav>
        <div className="mt-7 flex items-center justify-between px-2"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-slate-400">Projects</p><button onClick={() => setProjectOpen(true)} className="rounded-md p-1 text-slate-400 hover:bg-slate-100" aria-label="Create project"><Plus size={16}/></button></div>
        <div className="mt-2 space-y-1">{projects.map((p, index) => <button key={p.id} style={{ transitionDelay: mobileOpen ? `${index * 60}ms` : "0ms" }} onClick={() => { setActiveId(p.id); setMobileOpen(false); setLoading(true); }} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm transition-all ${p.id === activeId ? "bg-slate-100 font-semibold text-slate-800" : "text-slate-500 hover:bg-slate-50"}`}><span className="size-2.5 rounded-full" style={{ background: p.color }}/><span className="truncate">{p.name}</span></button>)}</div>
        <div className="absolute bottom-5 left-4 right-4 rounded-2xl bg-slate-900 p-4 text-white"><div className="mb-2 flex items-center gap-2 text-xs font-semibold"><Sparkles size={15} className="text-sky-400"/>Free workspace</div><div className="h-1.5 overflow-hidden rounded-full bg-slate-700"><div className="h-full w-3/5 rounded-full bg-sky-400"/></div><p className="mt-2 text-[11px] text-slate-400">3 of 5 team seats used</p></div>
      </aside>
      <section className="min-w-0 flex-1 p-4 md:p-7 lg:p-9"><div className="mx-auto max-w-[1500px]">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[.15em] text-sky-600">Active project</p><h1 className="font-heading text-2xl font-extrabold tracking-tight sm:text-3xl">{active?.name ?? "Your workspace"}</h1><p className="mt-1 text-sm text-slate-500">Plan, prioritize, and keep the work moving.</p></div><div className="flex gap-2"><button onClick={archiveProject} className="inline-flex items-center gap-2 rounded-lg border bg-white px-3.5 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><Archive size={16}/>Archive</button><button onClick={() => setTaskOpen(true)} className="inline-flex items-center gap-2 rounded-lg bg-sky-500 px-4 py-2 text-sm font-bold text-white shadow-lg shadow-sky-200 hover:bg-sky-600"><Plus size={17}/>Add task</button></div></div>
        <div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{statuses.map(s => <div key={s.id} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={`size-2.5 rounded-full ${s.color}`}/><span className="text-sm font-semibold text-slate-500">{s.label}</span></div><span className="font-heading text-2xl font-extrabold">{counts[s.id] ?? 0}</span></div></div>)}<div className="rounded-2xl bg-slate-900 p-4 text-white shadow-sm sm:col-span-2 xl:col-span-1"><div className="flex items-center justify-between"><span className="text-sm font-semibold text-slate-300">Completion</span><span className="font-heading text-2xl font-extrabold">{completion}%</span></div><div className="mt-3 h-1.5 rounded-full bg-slate-700"><div className="h-full rounded-full bg-emerald-400 transition-all" style={{ width: `${completion}%` }}/></div></div></div>
        <div className="mt-6 grid gap-4 lg:grid-cols-3">{statuses.map(status => <div key={status.id} onDragOver={e => e.preventDefault()} onDrop={() => { if (dragged) moveTask(dragged, status.id); setDragged(null); }} className="min-h-[430px] rounded-2xl bg-slate-100/80 p-3.5 ring-1 ring-slate-200/70"><div className="mb-3 flex items-center justify-between px-1"><div className="flex items-center gap-2"><status.icon size={17} className="text-slate-500"/><h2 className="font-heading text-sm font-bold">{status.label}</h2><span className="rounded-full bg-white px-2 py-0.5 text-[11px] font-bold text-slate-500">{counts[status.id] ?? 0}</span></div><button onClick={() => setTaskOpen(true)} className="rounded-lg p-1.5 text-slate-400 hover:bg-white" aria-label={`Add task to ${status.label}`}><Plus size={17}/></button></div>
          <div className="space-y-3">{loading ? [1,2].map(i => <div key={i} className="h-32 animate-pulse rounded-xl bg-white"/>) : filtered.filter(t => t.status === status.id).map(task => <article draggable onDragStart={() => setDragged(task.id)} key={task.id} className={`group cursor-grab rounded-xl border-l-4 bg-white p-4 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-0.5 hover:shadow-md ${priorityStyles[task.priority].split(" ")[0]}`}><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-bold leading-5">{task.title}</h3><button onClick={() => removeTask(task.id)} className="rounded p-1 text-slate-300 opacity-0 hover:bg-rose-50 hover:text-rose-500 group-hover:opacity-100 focus:opacity-100" aria-label="Delete task"><Trash2 size={15}/></button></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{task.description || "No description added"}</p><div className="mt-4 flex items-center justify-between"><span className={`rounded-full px-2 py-1 text-[9px] font-extrabold uppercase tracking-wider ${priorityStyles[task.priority].split(" ").slice(1).join(" ")}`}>{task.priority}</span><div className="flex items-center gap-2"><select value={task.status} onChange={e => moveTask(task.id, e.target.value as Status)} className="max-w-24 rounded-md border-0 bg-slate-50 px-1 py-1 text-[10px] font-semibold text-slate-500 outline-none"><option value="todo">To do</option><option value="in-progress">In progress</option><option value="done">Done</option></select><span className="grid size-7 place-items-center rounded-full bg-slate-800 text-[9px] font-bold text-white">{task.assignee || "ME"}</span></div></div></article>)}</div>
        </div>)}</div>
      </div></section>
    </div>
    <button onClick={() => setTaskOpen(true)} className="fixed bottom-5 right-5 z-30 grid size-14 place-items-center rounded-full bg-sky-500 text-white shadow-xl shadow-sky-300 transition hover:scale-105 md:hidden" aria-label="Quick add task"><Plus size={25}/></button>
    {taskOpen && <TaskModal projectId={activeId} onClose={() => setTaskOpen(false)} onSaved={loadTasks}/>} {projectOpen && <ProjectModal onClose={() => setProjectOpen(false)} onSaved={loadProjects}/>} 
  </main>;
}

function TaskModal({ projectId, onClose, onSaved }: { projectId: number | null; onClose: () => void; onSaved: () => void }) { const [saving, setSaving] = useState(false); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setSaving(true); const f = new FormData(e.currentTarget); await fetch("/api/tasks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ project_id: projectId, title: f.get("title"), description: f.get("description"), priority: f.get("priority"), status: f.get("status"), assignee: f.get("assignee") }) }); setSaving(false); onSaved(); onClose(); } return <Modal title="Create a new task" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Task title"><input name="title" required autoFocus placeholder="What needs to get done?" className="input"/></Field><Field label="Description"><textarea name="description" rows={3} placeholder="Add useful context for your team" className="input resize-none"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Priority"><select name="priority" className="input"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></Field><Field label="Status"><select name="status" className="input"><option value="todo">To do</option><option value="in-progress">In progress</option><option value="done">Done</option></select></Field></div><Field label="Assignee initials"><input name="assignee" maxLength={2} placeholder="AM" className="input uppercase"/></Field><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2 text-sm font-semibold">Cancel</button><button disabled={saving || !projectId} className="rounded-lg bg-sky-500 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{saving ? "Saving…" : "Create task"}</button></div></form></Modal>; }
function ProjectModal({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) { const [saving,setSaving]=useState(false); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setSaving(true); const f=new FormData(e.currentTarget); await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:f.get("name"),color:f.get("color")})}); await onSaved(); onClose(); } return <Modal title="Create a project" onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="Project name"><input className="input" name="name" required autoFocus placeholder="Product launch"/></Field><Field label="Project color"><input className="h-11 w-full cursor-pointer rounded-lg border p-1" type="color" name="color" defaultValue="#0EA5E9"/></Field><button disabled={saving} className="w-full rounded-lg bg-sky-500 py-2.5 text-sm font-bold text-white">{saving?"Creating…":"Create project"}</button></form></Modal> }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm" onMouseDown={e => { if(e.target===e.currentTarget) onClose(); }}><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h2 className="font-heading text-xl font-extrabold">{title}</h2><button onClick={onClose} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100" aria-label="Close dialog"><X size={19}/></button></div>{children}</div></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-xs font-bold text-slate-600">{label}<div className="mt-1.5">{children}</div></label> }
